---
title: "Transparency and Information Integrity"
---


Online platforms shape public debate, access to information, and modes of expression in ways that are often opaque and misaligned with the public interest. Given their substantial societal influence, effective scrutiny and accountability are urgent—and both rely on access to platform data. Researchers and civil society have used such data to uncover how harmful phenomena operate within these ecosystems at an unprecedented scale, and to assess how platform features may generate or amplify societal harms, particularly for vulnerable groups. These harms include coordinated disinformation campaigns and foreign influence operations that spread conspiracy theories and manipulate elections, hate speech targeting minorities and other social groups, and the recruitment and mobilisation of terrorist or neo-Nazi actors, often reinforced by platform monetisation mechanisms [@Benkler2018_networkpropaganda; @Bradshaw2019_disinformation; @Davey2019_replacement; @Marwick2017_media; @Tucker2018_socialmedia].

Exposing these dynamics through critical research has increased the risks to platforms' reputations and invited regulatory oversight, making those responsible for the calls for transparency clear targets of platform discontent [@Bruns2019_apicalypse; @Tromble2021_data]. Several platforms have discontinued previously available data access tools, such as APIs, often replacing them with weaker and less effective alternatives [@Bruns2019_apicalypse; @Freelon2018_postapi]. Recent evidence reinforces this concern: over 60% of researchers surveyed by the Coalition for Independent Technology Research reported facing barriers to accessing the data essential for studying how technology affects society [@CITR2025_powerinnumbers].

::: {.callout-note appearance="simple"}
*Data Not Found, Democracy at Risk: The curious case of Călin Georgescu*

The 2024 presidential election in Romania brought to light the dangers of social media data opacity. Călin Georgescu, a far-right, pro-Russian candidate dealing in conspiracy theories and nationalist tropes, went from political invisibility to electoral success through a seemingly well-orchestrated online blitz. Two weeks before the first round, Georgescu was languishing in the opinion polls, struggling for political relevance. On the night of 24 November, he was celebrating a shocking victory and preparing to face the liberal Elena Lasconi in the runoff [@Henley2024_romania].

The electoral upset was followed by accusations of campaign fraud and allegations of a Foreign Information, Manipulation and Interference operation led by Russia. In the wake of the public outcry and supported by intelligence reports uncovering financial irregularities and a wave of foreign cyberattacks [@Rainsford2024_romania], the Romanian Constitutional Court annulled the first round of the presidential election just two days ahead of the second round. This decision plunged Romania in a political turmoil for months, threatening the integrity of the democratic process in the country.

What happened? Regardless of the discussions surrounding the legitimacy and legality of the decisions to cancel the election and ban Georgescu, how could an extremely online fringe political figure become a mainstream national candidate vying for the presidential election in a matter of weeks without raising any alarm bells? Under the current social media data access restrictions, several pieces of information have been assembled but the puzzle has not been solved. Since November 2024, Romanian and international organisations have been combing through the dearth of data in an effort to inspect the social media data and algorithmic black boxes. These exercises of digital forensics found traces of a sophisticated online architecture supported by foreign actors [@Nutu2025_efor; @Olari2024_romania].

Georgescu bypassed the traditional electoral campaign and relied almost exclusively on the network effects of social media platforms, like Telegram, Facebook and TikTok. According to some investigations [@Nutu2025_efor; @Olari2024_romania], the candidate’s social media engagement grew exponentially in the weeks preceding the election, which allowed him to reach more young voters in the country and in the Romanian diaspora. Although Georgescu’s campaign declared zero spending, the Romanian intelligence service claimed to have found digital footprints of foreign manipulation and irregular campaign funding used to promote the candidate on TikTok [@Rainsford2024_romania].

In yet another demonstration of the shortcomings of online self-regulation, TikTok had banned political advertising in 2019 [@Chandlee2019_tiktokads]. This decision, however, did not prevent the platform from becoming the main hub for an online campaign that undermined the democratic process in a EU member country. Under the DSA, the European Commission issued a retention order to TikTok, instructing the platform to preserve all data related to systemic risks against democratic electoral processes [@EuropeanCommission2024b_romania]. Too little, too late. Only the implementation and enforcement of robust frameworks that ensure access to user-generated and advertising data will allow the effective monitoring and facilitate the prevention of online manipulation and fraud.
:::

Researcher access to data is particularly important for understanding both the problems and potential solutions associated with global technology harms. The global scientific community has identified issues such as child exploitation, technology-facilitated harms, and climate misinformation as areas where constraints on access to platform data are limiting our ability to generate evidence and respond effectively to these challenges [@Pothong2026_disrupting].

Against this backdrop, the United Nations (UN) and other international bodies have situated data transparency within the emerging debate on so-called information integrity. Broadly speaking, information integrity refers to information that is reliable, accurate, and accessible to all, that empowers people to engage in public life and debate, and is shaped by governments, technology companies, media organisations, civil society, and individuals alike [@UN2025_practice]. More broadly, any factor that undermines users' ability to access accurate, consistent, and reliable information, free from manipulation and falsehoods, constitutes a threat to information integrity [@EuropeanParliament2024_information; @UN_2024_InformationIntegrity].

Achieving information integrity requires mitigating risks such as disinformation, hate speech, and toxic discourse in the wider sense. The UN has identified some of these risks as major global vulnerabilities that can arise from the malicious use of technology. Mitigation measures, in turn, involve identifying adversaries—including individuals, groups, organisations, and both State and non-State actors—along with their tactics and objectives, while carefully considering potential outcomes. These disruptions threaten democratic governance, human rights, peace, and effective responses to environmental and health crises, hindering public understanding, informed debate, and evidence-based decision-making [@UN2025_practice].

Building an information ecosystem with integrity requires safeguarding freedom of expression and ensuring the free, safe, and inclusive flow of information, while respecting individual privacy. In this context, the UN's principles for strengthening information integrity, set out in a call for multistakeholder action, focus on key pillars such as supporting independent, free, and pluralistic media, empowering citizens, and, most relevant to this study, ensuring that platforms provide transparency guarantees for public-interest research [@UN_2024_InformationIntegrity]. Notably, Research is one of the pillars of the UN's 3R approach to information integrity, alongside Response (Prevention, Protection, Mitigation, Recovery) and Risk (Assessment) [@UN2025_practice].

Access to data for public-interest research offers a way to bridge the gap between platforms and citizens by addressing a longstanding asymmetry: while platforms know a great deal about their users, users know very little about social media dynamics. Research based on online platform data ultimately enables measurements for platforms' impacts on society through observing human behaviour in real-world environments [@Marres2017_digital; @Rogers2009_virtual; @VanAtteveldt2018_communication].

The potential of such investigations to inform the design and revision of public policies should not be underestimated. The UN's Information Integrity Theory of Change broadly argues that research based on open data fosters public awareness and evidence-based insights, which in turn support more informed decision-making [@UN2025_practice]. 

::: {.callout-note appearance=”simple”}
*Data not Found, Investment at risk: Is digital advertising a racket?* Digital advertising is an example of a perfectly imperfect information market. Advertisers struggle to reliably estimate return on investment, while users are reduced to monetised data points. The market is controlled by online services and social media platforms selling virtual spaces and algorithms that promise microtargeted brand-user connection. Advertisers and investors continue to believe in the efficiency of this unverifiable mechanism.

Evidence has long cast doubt on these assumptions. In 2021, Forbes reported cases of companies withdrawing from digital advertising without measurable losses in sales or revenue [@Fou2021_digitalads]. Earlier, a large-scale experiment by eBay Research Labs found that paid search advertising produced “no measurable short-term benefit” [@Blake2015_heterogeneity], prompting the company to scale back its investment.

Oblivious to the warning signs, the digital marketplace continued to expand. In 2017, the consumer-goods giant Procter & Gamble cut USD 200 million in digital ad spending after identifying significant limitations in targeting effectiveness. Marc Pritchard, the Chief Brand Officer of Procter & Gamble, made an illuminating declaration: “transparency \[shined\] a spotlight on reality and we learned valuable lessons which are driving profound change” [@Cavale2018_pg].

These market experiments by two leading players of the new and old economies unveiled deep-rooted structural problems: underneath the inflated claims of reach, impressions and microtargetting, lies an inefficient and often fraudulent market [@Schiffrin2026_deepfake] that has grown ever more opaque.

At the same time, a growing “attention crisis” further undermines the model. Users increasingly rely on ad-blocking technologies, while shifts toward AI-mediated search and interaction reduce the visibility and relevance of traditional ads. As more online activity takes place through AI systems rather than search engines or websites, the link between ad exposure and consumer behaviour becomes even more tenuous.

The near-future looks grim. At its most farcical, digital advertising risks devolving into a synthetic loop in which AI-generated ads are delivered primarily to automated bots. At its most serious, it could resemble less a marketplace and more a financial racket. This trajectory underscores the urgent need for greater transparency. Technical complexity and platform opacity should not preclude independent scrutiny or accountability. Advertisers, investors, researchers, and the public must have meaningful access to data on how digital advertising systems operate, as well as robust safeguards against abusive practices. Moving toward a more symmetrical information environment is therefore essential. Data transparency in digital advertising is not only a matter of market efficiency, but a financial imperative and a fundamental consumer right.
:::

Moreover, the UN argues that debates on data access and transparency must be grounded in robust data quality principles to support accountability and informed policymaking, particularly in light of enduring power asymmetries and emerging risks, such as the rising use of generative AI for public-opinion manipulation [@UN_2024_InformationIntegrity]. Indeed, data quality is a central concern in data governance and lifecycle management. Making data available is only a baseline requirement: it must also meet a set of quality criteria that determine whether it is suitable for specific analytical or policy purposes [@Batini2016_dataquality; @Benson2019_iso8000; @Mahanti2019_dataquality]. In the context of social research, ensuring data quality is essential for guaranteeing the reliability and reproducibility of studies, as well as enabling generalisations [@Srivastava2023_analyzing].

In fact, many researchers have previously questioned the quality of the data that platforms make available. For instance, researchers have long raised concerns about which data is made available, particularly regarding sampling and representativeness [@Tufekci2014_bigquestions]. Data made available through APIs and advertising repositories may also become unavailable or degrade over time, while researchers frequently face challenges related to outdated metrics and incomplete information [@Angus2024_computational; @Edelson2020_facebook; @Zubiaga2018_longitudinal]. We structure our analysis around established data quality dimensions, allowing us to assess not only whether data is made available, but also the conditions under which access is granted, as detailed in our methodological complement, available online.

# Guideline Documents

| Reference | Description |
| :---- | :---- |
| **[ITU/UNESCO Broadband Commission](https://unesdoc.unesco.org/ark:/48223/pf0000379015)**[. Balancing Act: Countering Digital Disinformation While Respecting Freedom of Expression (2020)](https://unesdoc.unesco.org/ark:/48223/pf0000379015) | Released in the context of the COVID-19 pandemic, the document includes measures aimed at combating the spread of disinformation. The report calls on stakeholders to promote equitable access to essential data held by internet communication companies in order to enable independent analyses of the incidence, dissemination, and impact of disinformation, particularly in the context of elections, public health, and natural disasters. To this end, it recommends providing broader access to their datasets for independent researchers—including those who do not receive significant research funding from these companies—with the aim of fostering knowledge sharing to counter disinformation. |
| **[UNESCO](https://unesdoc.unesco.org/ark:/48223/pf0000380455)**[. Recommendation on the Ethics of Artificial Intelligence (2021)](https://unesdoc.unesco.org/ark:/48223/pf0000380455) | The document delineates ethical issues related to artificial intelligence. In it, UNESCO recommends that states ensure that individuals' personal data are protected by a framework that promotes transparency, effective accountability mechanisms, and independent oversight bodies as part of broader governance arrangements. |
| **[Council of Europe](https://rm.coe.int/0900001680a6172e)**[. Recommendation CM/Rec(2022)12 of the Committee of Ministers to Member States on Electoral Communication and Media Coverage of Election Campaigns (2022)](https://rm.coe.int/0900001680a6172e) | The recommendations specifically address political ads, indicating that platforms maintain open and machine-readable archives of such ads, ensuring scrutiny by relevant authorities, independent advisory bodies, academia, election observers, and civil society. The report also encourages the development of co-regulation mechanisms to promote greater transparency in the political advertising ecosystem. |
| **[United Nations General Assembly](https://documents.un.org/doc/undoc/gen/n22/459/24/pdf/n2245924.pdf)**[. Countering Disinformation for the Promotion and Protection of Human Rights and Fundamental Freedoms (A/77/287) (2022)](https://documents.un.org/doc/undoc/gen/n22/459/24/pdf/n2245924.pdf) | The document outlines the challenges faced by states in combating disinformation. It acknowledges that states have increasingly engaged in discussions on regulatory frameworks that require greater transparency in the operation of platforms, thereby enabling independent auditing. These efforts involve enhancing clarity around advertising, particularly political advertising and its sources of funding, as well as expanding access for researchers and other stakeholders to data held by platforms. The report also acknowledges that access to data is essential for enabling the monitoring and evaluation of the impacts of new regulations concerning digital services. |
| **[OECD.](https://www.oecd.org/en/publications/2024/03/facts-not-fakes-tackling-disinformation-strengthening-information-integrity_ff96d19f.html)** [Facts not Fakes: Tackling Disinformation, Strengthening Information Integrity (2024)](https://www.oecd.org/en/publications/2024/03/facts-not-fakes-tackling-disinformation-strengthening-information-integrity_ff96d19f.html) | The report explores ways of responding to the phenomenon of disinformation in order to safeguard democracy. It recommends the establishment of mechanisms that enable governments and independent researchers to verify information about ads disseminated by platforms. It also proposes the creation of mechanisms to ensure the conduct of high-quality research involving advertising data. |
| **[OECD Council.](https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0505)** [Recommendation of the Council on Information Integrity (2024)](https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0505) | The proposal recommends that online platforms create advertising databases that are accessible and include archived ads, even after they have been removed, to increase transparency and oversight over where ads are displayed and provide greater access to ads details to individuals and researchers. It also recommends greater access to public and non-public data and information by providing a dedicated data sharing infrastructure to monitor potential information integrity risks, while ensuring appropriate and sufficient privacy and data protection measures to prevent harmful outcomes for data subjects, including, for example, by limiting data access to independent researchers, civil society organisations, and journalists who meet specific requirements that ensure appropriate handling related to user privacy, security, and proprietary considerations. |
| **[United Nations.](https://www.esteri.it/wp-content/uploads/2024/06/un-global-principles-for-information-integrity-en.pdf)** [Global Principles For Information Integrity. Recommendations for Multi-stakeholder Action (2024)](https://www.esteri.it/wp-content/uploads/2024/06/un-global-principles-for-information-integrity-en.pdf) | The Principles recommend that platforms maintain full, accessible, up-to-date and searchable advertising libraries with information on the source or purchaser, how much was spent and the target audience; give detailed data to advertisers and researchers on exactly where adverts have appeared; provide researchers, including academics across disciplines, journalists, civil society and international organisations, access to the data that they need to better understand information integrity, inform policy and best practice and improve accountability, while respecting user privacy and intellectual property; facilitate data delivery for researchers at minimal cost in accessible, machine-readable formats. |
| [**United Nations General Assembly**. Pact for the Future (A/79/L.2) (2024)](https://docs.un.org/en/A/79/L.2)  | The draft calls on digital technology companies and social media platforms to enhance the transparency and accountability of their systems, including their terms of service, content moderation and recommendation algorithms, as well as their data practices concerning users' personal data, in order to empower users to make informed choices and to provide or withdraw informed consent. Moreover, it recommends providing researchers with access to platform data, subject to safeguards for user privacy, in order to ensure transparency and accountability and to build an evidence base on how to address misinformation, disinformation, and hate speech. |
| [**United Nations Human Rights Council**. Freedom of Expression and Elections in the Digital Age: Report of the Special Rapporteur on the Promotion and Protection of the Right to Freedom of Opinion and Expression (A/HRC/59/50) (2025)](https://docs.un.org/en/A/HRC/59/50) | The report suggests that combating disinformation should not depend solely on content moderation, but also on greater openness about platform practices, allowing for public and regulatory scrutiny. It acknowledges that platforms do not offer adequate levels of transparency to enable effective content monitoring. It states that visibility into Meta's content moderation practices, including its role in the 2024 elections, is "near zero"; that Google, X, and Meta reportedly resisted data requests from the Electoral Commission of South Africa; that Meta made it more difficult to access data after deactivating CrowdTangle; and that X has made it prohibitively expensive for researchers to obtain its data via APIs. Moreover, it highlights the need for better information, noting that even where platform data is available, there can be significant inconsistencies in content and format, making research and comparison difficult. |

## References {.unnumbered}

::: {#refs}
:::
